<?php
//////////////////////////////////////////////////////////////////////////////
// Copyright (C) 2019 - Tinh Truong                                         //
//									                                        //
// Date:		24/06/2019													//
// Created by:	Tinh Truong @edna.life                                      //
//                                                                          //
// This source code is subject to commerical confidentiality and may not be //
// disclosed to unauthorised thrid parties without written permission from  //
// the owner.																//
//////////////////////////////////////////////////////////////////////////////
require_once("eosio_chain.inc");

class Block extends EosioChain{


}
